<a href="https://colab.research.google.com/github/lokanathsql/test_repo/blob/main/Copy_of_Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## import libraries

In [ ]:

from pymongo import MongoClient
import pandas as pd


from pymongo import MongoClient
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/DAS7001_PRAC1/WorldCupMatches.csv')

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Year,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,Attendance,HalftimeHomeGoals,HalftimeAwayGoals,Referee,Assistant1,Assistant2,RoundID,MatchID,HomeTeamInitials,AwayTeamInitials
0,1982,Group 3,Camp Nou,Barcelona,Argentina,0,1,Belgium,95000.0,0,0,CHRISTOV Vojtech (TCH),PALOTAI Karoly (HUN),JARGUZ Alojzy (POL),293,749,ARG,BEL
1,1982,Group 1,Estadio Municipal de BalaÔøΩdos,Vigo,Italy,0,0,Poland,33000.0,0,0,VAUTROT Michel (FRA),PROKOP Adolf (GDR),RAINEA Nicolae (ROU),293,995,ITA,POL
2,1982,Group 6,Ramon Sanchez Pizjuan,Seville,Brazil,2,1,Soviet Union,68000.0,0,1,LAMO CASTILLO Augusto (ESP),SANCHEZ ARMINIO Victoriano (ESP),GARCIA CARRION Jose L. (ESP),293,791,BRA,URS
3,1982,Group 1,Riazor,La CoruÔøΩA,Peru,0,0,Cameroon,11000.0,0,0,WOEHRER Franz (AUT),RAINEA Nicolae (ROU),PROKOP Adolf (GDR),293,833,PER,CMR
4,1982,Group 3,Nuevo Estadio,Elche,Hungary,10,1,El Salvador,23000.0,3,0,AL DOY Ebrahim (BHR),CORVER Charles (NED),LUND-SORENSEN Henning (DEN),293,896,HUN,SLV

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## connect mongodb atlas

In [ ]:
client = MongoClient(
    "mongodb+srv://lokanathsql_db_user:dYPzPSOgJqvUNzYh@cluster0.qkfrgxt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
)

db = client["WorldCupDB"]

collection = db["matches"]

print("MongoDB Connected Successfully")

MongoDB Connected Successfully

## load csv file

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/DAS7001_PRAC1/WorldCupMatches.csv")

df = df.fillna("")

df.head()

,Year,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,Attendance,HalftimeHomeGoals,HalftimeAwayGoals,Referee,Assistant1,Assistant2,RoundID,MatchID,HomeTeamInitials,AwayTeamInitials
0,1982,Group 3,Camp Nou,Barcelona,Argentina,0,1,Belgium,95000.0,0,0,CHRISTOV Vojtech (TCH),PALOTAI Karoly (HUN),JARGUZ Alojzy (POL),293,749,ARG,BEL
1,1982,Group 1,Estadio Municipal de BalaÔøΩdos,Vigo,Italy,0,0,Poland,33000.0,0,0,VAUTROT Michel (FRA),PROKOP Adolf (GDR),RAINEA Nicolae (ROU),293,995,ITA,POL
2,1982,Group 6,Ramon Sanchez Pizjuan,Seville,Brazil,2,1,Soviet Union,68000.0,0,1,LAMO CASTILLO Augusto (ESP),SANCHEZ ARMINIO Victoriano (ESP),GARCIA CARRION Jose L. (ESP),293,791,BRA,URS
3,1982,Group 1,Riazor,La CoruÔøΩA,Peru,0,0,Cameroon,11000.0,0,0,WOEHRER Franz (AUT),RAINEA Nicolae (ROU),PROKOP Adolf (GDR),293,833,PER,CMR
4,1982,Group 3,Nuevo Estadio,Elche,Hungary,10,1,El Salvador,23000.0,3,0,AL DOY Ebrahim (BHR),CORVER Charles (NED),LUND-SORENSEN Henning (DEN),293,896,HUN,SLV

## insert csv to mongodb

In [ ]:
data = df.to_dict(orient='records')

collection.insert_many(data)

print("World Cup Dataset Inserted Successfully")

ServerSelectionTimeoutError: SSL handshake failed: ac-bqokdej-shard-00-01.qkfrgxt.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-bqokdej-shard-00-02.qkfrgxt.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-bqokdej-shard-00-00.qkfrgxt.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6a047075f0d0bb456cce236f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-bqokdej-shard-00-00.qkfrgxt.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-bqokdej-shard-00-00.qkfrgxt.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-bqokdej-shard-00-01.qkfrgxt.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-bqokdej-shard-00-01.qkfrgxt.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-bqokdej-shard-00-02.qkfrgxt.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-bqokdej-shard-00-02.qkfrgxt.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

## Insert Additional Documents with Missing Fields

In [ ]:
extra_docs = [

    {
        "Year": 2026,
        "Stage": "Quarter-finals",
        "HomeTeamName": "India",
        "AwayTeamName": "Japan"
    },

    {
        "Year": 2026,
        "Stage": "Semi-finals",
        "HomeTeamName": "Brazil",
        "AwayTeamName": "Germany",
        "HomeTeamGoals": 2
    },

    {
        "Year": 2026,
        "Stage": "Final",
        "HomeTeamName": "Argentina",
        "AwayTeamName": "France"
    },

    {
        "Year": 2026,
        "Stage": "Group Stage",
        "HomeTeamName": "Spain",
        "AwayTeamName": "Portugal"
    },

    {
        "Year": 2026,
        "Stage": "Round of 16",
        "HomeTeamName": "England",
        "AwayTeamName": "Italy"
    }
]

collection.insert_many(extra_docs)

print("Extra Documents Inserted Successfully")

NameError: name 'collection' is not defined

## QUERY 1 — Display Quarter Final Matches

In [ ]:
for match in collection.find({"Stage": "Quarter-finals"}):
    print(match)

## QUERY 2 — Display Selected Columns

In [ ]:
for match in collection.find(
    {},
    {
        "Year": 1,
        "Stage": 1,
        "HomeTeamName": 1,
        "AwayTeamName": 1,
        "_id": 0
    }
):
    print(match)

## QUERY 3 — Display Final Matches

In [ ]:
for match in collection.find({"Stage": "Final"}):
    print(match)

## QUERY 4 — Delete Documents Where HomeTeamGoals = 0

In [ ]:
result = collection.delete_many({"HomeTeamGoals": 0})

print(result.deleted_count, "documents deleted")

## QUERY 5 — Update RoundID

In [ ]:
result = collection.update_many(
    {"RoundID": 308},
    {"$set": {"RoundID": 30800}}
)

print(result.modified_count, "documents updated")

NameError: name 'collection' is not defined

## QUERY 6 — Delete Referee Names Starting with S

In [ ]:
result = collection.delete_many(
    {"Referee": {"$regex": "^S"}}
)

print(result.deleted_count, "documents deleted")